#!/usr/bin/env node

/**
 * [nct : node cli tools]
 * @author: xgqfrms
 * @date: 2017-06-12
 */

const nct = require('./libs');

let username = process.argv[2] ? process.argv[2] : `xgqfrms-GitHub`;
    repo = process.argv[3] ? process.argv[3] : `Node-CLI-Tools`;

nct(username, repo);
